// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using QiQiBot.Models;

#nullable disable

namespace QiQiBot.Migrations
{
    [DbContext(typeof(ClanContext))]
    [Migration("20260217200754_CapStats")]
    partial class CapStats
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("QiQiBot.Models.Clan", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("LastScraped")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_scraped");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("clans", "qiqi");
                });

            modelBuilder.Entity("QiQiBot.Models.Guild", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal?>("AchievementsChannelId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("achievements_channel_id");

                    b.Property<long?>("CapResetDay")
                        .HasColumnType("bigint")
                        .HasColumnName("cap_reset_day");

                    b.Property<long?>("CapResetTime")
                        .HasColumnType("bigint")
                        .HasColumnName("cap_reset_time");

                    b.Property<long?>("ClanId")
                        .HasColumnType("bigint")
                        .HasColumnName("clan_id");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("guild_id");

                    b.HasKey("Id");

                    b.HasIndex("ClanId");

                    b.HasIndex("GuildId")
                        .IsUnique();

                    b.ToTable("guilds", "qiqi");
                });

            modelBuilder.Entity("QiQiBot.Models.Player", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ClanExperience")
                        .HasColumnType("bigint")
                        .HasColumnName("clan_experience");

                    b.Property<long?>("ClanId")
                        .HasColumnType("bigint")
                        .HasColumnName("clan_id");

                    b.Property<bool>("InvalidRuneMetricsProfile")
                        .HasColumnType("boolean")
                        .HasColumnName("invalid_runemetrics_profile");

                    b.Property<DateTime?>("LastCapped")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_capped");

                    b.Property<DateTime?>("LastClanExperienceUpdate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_clan_experience_update");

                    b.Property<DateTime?>("LastScrapedRuneMetricsProfile")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_scraped_runemetrics_profile");

                    b.Property<DateTime?>("MostRecentRuneMetricsEvent")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("most_recent_runemetrics_event");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<bool>("PrivateRuneMetricsProfile")
                        .HasColumnType("boolean")
                        .HasColumnName("private_runemetrics_profile");

                    b.HasKey("Id");

                    b.HasIndex("ClanId");

                    b.HasIndex("LastScrapedRuneMetricsProfile");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("players", "qiqi");
                });

            modelBuilder.Entity("QiQiBot.Models.Guild", b =>
                {
                    b.HasOne("QiQiBot.Models.Clan", "Clan")
                        .WithMany("Guilds")
                        .HasForeignKey("ClanId");

                    b.Navigation("Clan");
                });

            modelBuilder.Entity("QiQiBot.Models.Player", b =>
                {
                    b.HasOne("QiQiBot.Models.Clan", "Clan")
                        .WithMany("ClanMembers")
                        .HasForeignKey("ClanId");

                    b.Navigation("Clan");
                });

            modelBuilder.Entity("QiQiBot.Models.Clan", b =>
                {
                    b.Navigation("ClanMembers");

                    b.Navigation("Guilds");
                });
#pragma warning restore 612, 618
        }
    }
}
